### ISSUE TITLE
Submission: <Gryffindor>

### ISSUE THREAD

**Issue by Subhraneel77** [gdgcloudkol/hackday#20]
### Team Name

Gryffindor

### Team members

Member # 1
Name : Subhraneel Haldar
Email : subhraneel777@gmail.com
Twitter handle (hyperlinked): https://twitter.com/subhraneel71 

Member # 2
Name: Prantik Dhara
Twitter handle (hyperlinked):

Member # 3
Name: PRIYA YADAV
Twitter handle (hyperlinked):

### Project Name

Faceracks

### Contact Details (Leader)

subhraneel777@gmail.com

### Project Track

Open Innovation

### Link to project GitHub public repo

https://github.com/Subhraneel77/Faceracks

### Link to demo video

https://drive.google.com/file/d/1k0zMwW1kPxPg7xRuXtGEfifBeOSgq2gM/view?usp=sharing

### Inspiration

First and the foremost matter is the evolution of Artificial Intelligence in our modern generation which has influenced as well as inspired us a lot. In this progressive era we can hardly can understand each other's mood swigs or personality traits but using this project we are able to successfully establish an AI which can approximately tell you your Current Mood, Your Look similarity percentage with any other person, Your approx age as well as your landmark detection. Policeman's along with any common-man can easily use this project to detect the personality traits of a human being. We are trying to discover and innovate new things time by time and trying to add lots of features in this project to make it useful for our nation.

### What it does

1) It helps us to predict any person's Current Mood, anyone's look similarity percentage with any other person, our approx age as well as our landmark detection.
2)After face detection, we can furthermore predict the facial landmarks for each detected face.
3)After face detection and facial landmark prediction the face descriptors for each face can be computed.
4)Age estimation and gender recognition from detected faces.
5) We can also have a Display of Results.

### Challenges you ran into

1) Firstly since our main Moto is to learn something new about this latest technology , so we have to do lots and lots of research and have to take help from lots of open source databases. Lots of modifications we are planning to do but currently it is under our plan to design this project with CSS templates in a much better way possible. Days after days we are constantly spending to find a single solution to make it better version of itself.
2) Lots of code read and had to verify with other codes and implement new features to it.
3) Lots of bugs are still required to be fix as it is just the beginning.

### Anything else?

1. This project is far from being perfect.
2. We need to provide security and bigger datasets for the model to train and analyze sentiments more effectively.
3. A lot of Design improvements can also be made.
4. Bugs needs to be fix to make it a flexible user-friendly project.

**Comment by xprilion** [comment]
@Subhraneel77 Please provide emails of all team members in a reply to this comment.

**Comment by Subhraneel77** [comment]
1. subhraneel777@gmail.com -SUBHRANEEL HALDAR
2. py8116937@gmail.com -- PRIYA YADAV
3. prantikdhara6@gmail.com --- PRANTIK DHARA

**Comment by xprilion** [comment]
Thanks. We noticed you've completely ripped off the entire project from [justadudewhohacks/face-api.js](https://github.com/justadudewhohacks/face-api.js/).

Besides being against the event rules, we believe this was a display of malicious ethics and thus, will not be entertaining any entries from all members of this project in any future GDG Cloud Kolkata hackathons for a duration of 1 year.

**Comment by Subhraneel77** [comment]
1. ***@***.*** -SUBHRANEEL HALDAR
   2. ***@***.*** -- PRIYA YADAV
   3. ***@***.*** --- PRANTIK DHARA
