### ISSUE TITLE
Submission: <Alpha Squad>

### ISSUE THREAD

**Issue by SauravMukherjee44** [gdgcloudkol/hackday#21]
### Team Name

Alpha Squad

### Team members

Member # 1
Name: Saurav Mukherjee
Email: mesouravofficial@gmail.com 
Twitter handle :[ mesourav44
](https://twitter.com/mesourav44)

Member # 2
Name: Bharti Kumari
Twitter handle : [bhartik021](https://twitter.com/bhartik021)

Member # 3
Name: Diya Vijay
Twitter handle : [DiyaVijay6](https://twitter.com/DiyaVijay6)

### Project Name

E-Library

### Contact Details (Leader)

mesouravofficial@gmail.com

### Project Track

Education

### Link to project GitHub public repo

https://github.com/SauravMukherjee44/E-Library

### Link to project website

https://e-library-online.netlify.app/

### Link to demo video

https://youtu.be/3bF2mxqh_c4

### Inspiration

In India, people find it boring to read books physically and that's why we launched E-Library to regain their interest in technologies.
The distribution process is controlled and centralized by E-Library, reducing the risk of book loss, over-ordering, and costly replacements. The E-Library provides simple information on each form of the system, as well as descriptions of each field on the form. In addition to being simple to use, E-Library can easily generate instant reports. The application is designed to be flexible and user-friendly. 

### What it does

This is an E-Library Website in which you get Resources to learn different topics, Donate book section to donate your old books, and a Book issue section to keep a record of all the books issued. This website helps you to find the books easily without any cost and the best part about the website is that you can also contribute to the website for others to use the resources by donating the books you have, all categories of books are welcome for donation. 

- Automatic fine calculation is available for late returns.
- Sort the books by subject.
- Store various books, journals, newspapers, magazines, etc.
- Checking in and checking out is quick and simple.
- A book can be searched using various criteria.
- New books can easily be added.
- A quick way to see how many books a student has received.
- Number of books, number of books issued, number of journals, and so on

### Challenges you ran into

We were facing an issue while integrating the frontend with our database and with the authentication. We had to read several docs related to this to solve this issue. Also, Throughout the process, we learned how to integrate it from scratch.

### Anything else?

![image](https://user-images.githubusercontent.com/72380920/185801058-a122f0fe-17f6-4908-86a6-c2d0e3ceb3db.png)

**Comment by xprilion** [comment]
Rip off of an own project - https://github.com/SauravMukherjee44/Aec-Library-Website
