### ISSUE TITLE
Submission: <Buidl>

### ISSUE THREAD

**Issue by heysagnik** [gdgcloudkol/hackday#5]
### Team Name

Buidl

### Team members

Member # 1
Name:Sagnik Sahoo 
Email: sahoosagnik1@gmail.com
Twitter handle (hyperlinked): [@heysagnik](https://twitter.com/heysagnik) 

### Project Name

ScreenREC 

### Contact Details (Leader)

sahoosagnik1@gmail.com

### Project Track

Open Innovation

### Link to project GitHub public repo

https://github.com/heysagnik/screenREC

### Link to project website

https://screen-rec.vercel.app/

### Link to demo video

https://screen-rec.vercel.app/

### Inspiration

Various Screen Recorders 

### What it does

It helps the user to record the screen just like any other screen Recorder. Just it's minimal UI,ad-free, Open Source.

### Challenges you ran into

- [x] Design a minimal UI
- [x] Code it by using Chrome ScreenShare api. 
- [ ] and ....

**Comment by heysagnik** [comment]
Why ?

**Comment by imanishbarnwal** [comment]
Because it's not a fresh project and its first commit was on `22nd June` [Link](https://github.com/heysagnik/screenREC/commit/a8572f177f1886a1df7d9339b55bcdc3c679b7a4).
